# Change these first
owner: davwheat # Your GitHub organization or username, where this repository lives
repo: api-status # The name of this repository

sites:
  - name: Huxley2
    url: https://national-rail-api.davwheat.dev/
    maxResponseTime: 15000
  - name: Flarum Badge API
    url: https://flarum-badge-api.davwheat.dev/v1/compat-latest/flarum/markdown
    maxResponseTime: 6000
  - name: Uploads server
    url: https://u.davwheat.dev/
    maxResponseTime: 7500

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.davwheat.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: davwheat.dev status
  introTitle: "View real-time status info about my sites and APIs."
  introMessage: View information about my websites and APIs, as well as tracking downtime and latency.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://davwheat.dev/
    - title: GitHub
      href: https://github.com/davwheat

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
  
assignees:
  - davwheat

# Removes footer attribution
# i18n:
#   footer: ""
